---
# Usage (flags are optional):
#  ansible-playbook deploy-webnode.yml -e flag1=keep-maintenance -e flag2=no-git
#  note: the flags can be swithed, flag1=no-git is also correct.
#  note: When no tasks complete check your syntax.

- name: deploy-webnode.yml
  hosts: all
  vars:
    flag1: "0"
    flag2: "0"

  tasks:

### Will check if new EC2 instances are added in AWS, and if so load the new facts ##
    - name: Playbook - Register local facts file
      command: cat /etc/hsl.def
      register: file_hsl_def
      changed_when: false

    - name: Playbook - Make the facts available for ansible
      copy:
        content: "[general]\n{{ file_hsl_def.stdout }}\n"
        dest: /etc/ansible/facts.d/custom.fact
        mode: 0644

    - name: Playbook - Regather facts - ansible_local
      setup:
        filter: ansible_local
################################################################################

    - name: "Playbook - update:webnode -v"
      shell: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:webnode -v"
      args:
        chdir: /
      register: shell_result
      when: (flag1 == "0" and flag2 == "0")

    - name: "Playbook - update:webnode -v --keep-maintenance"
      shell: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:webnode -v --keep-maintenance"
      args:
        chdir: /
      register: shell_result
      when: (flag1 == "keep-maintenance" and flag2 == "0") or (flag1 == "0" and flag2 == "keep-maintenance")

    - name: "Playbook - update:webnode -v --no-git"
      shell: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:webnode -v --no-git"
      args:
        chdir: /
      register: shell_result
      when: (flag1 == "0" and flag2 == "no-git") or (flag1 == "no-git" and flag2 == "0")

    - name: "Playbook - update:webnode -v --no-git --keep-maintenance"
      shell: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:webnode -v --no-git --keep-maintenance"
      args:
        chdir: /
      register: shell_result
      when: (flag1 == "keep-maintenance" and flag2 == "no-git") or (flag1 == "no-git" and flag2 == "keep-maintenance")

    - name: "Playbook - update:webnode - Shell Standard Output"
      debug:
        var: shell_result.stdout_lines

    - name: "Playbook - update:webnode - Shell Standard Error"
      debug:
        var: shell_result.stderr
