---
# Usage (flags are optional):
#  ansible-playbook deploy-webnode.yml -e flag1=keep-maintenance -e flag2=no-git
#  note: the flags can be swithed, flag1=no-git is also correct.
#  note: When no tasks complete check your syntax.

- name: deploy-webnode.yml
  hosts: all
  vars:
    flag1: "0"
    flag2: "0"

  tasks:
    - name: "command: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/n98-magerun2.phar maintenance:enable -v"
      shell: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:admin -v
      args:
        chdir: /
      when: (flag1 == "0" and flag2 == "0")

    - name: "command: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/n98-magerun2.phar maintenance:enable --keep-maintenance"
      shell: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:admin -v --keep-maintenance
      args:
        chdir: /home/admin/
      when: (flag1 == "keep-maintenance" and flag2 == "0") or (flag1 == "0" and flag2 == "keep-maintenance")

    - name: "command: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/n98-magerun2.phar maintenance:enable"
      shell: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:admin -v --no-git
      args:
        chdir: /home/admin/
      when: (flag1 == "0" and flag2 == "no-git") or (flag1 == "no-git" and flag2 == "0")

    - name: "command: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/n98-magerun2.phar maintenance:enable"
      shell: /var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/bin/deploy update:admin -v --no-git --keep-maintenance
      args:
        chdir: /home/admin/
      when: (flag1 == "keep-maintenance" and flag2 == "no-git") or (flag1 == "no-git" and flag2 == "keep-maintenance")
