# Usage:
#  ansible-playbook deploy-pwa.yml

- name: deploy-pwa.yml
  hosts: all,localhost

  tasks:

### Will check if new EC2 instances are added in AWS, and if so load the new facts ##
    - name: Playbook - Register local facts file
      command: cat /etc/hsl.def
      register: file_hsl_def
      changed_when: false

    - name: Playbook - Make the facts available for ansible
      copy:
        content: "[general]\n{{ file_hsl_def.stdout }}\n"
        dest: /etc/ansible/facts.d/custom.fact
        mode: 0644

    - name: Playbook - Regather facts - ansible_local
      setup:
        filter: ansible_local
################################################################################

    - name: "Playbook - check pwa directory"
      shell: "if [ -d spstorefront ]; then echo 'true'; else echo 'false'; fi"
      args:
        chdir: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs"
      register: pwadir

    - name: "Playbook - run npm install"
      shell: "npm install"
      args:
        chdir: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/spstorefront"
      register: shell_result
      when: pwadir.stdout == "true"

    - name: "Playbook - run npm install - Shell Standard Output"
      debug:
        var: shell_result.stdout_lines
      when: pwadir.stdout == "true"

    - name: "Playbook - run npm install - Shell Standard Error"
      debug:
        var: shell_result.stderr
      when: pwadir.stdout == "true"

    - name: "Playbook - run npm build"
      shell: "npm run build"
      args:
        chdir: "/var/www/vhosts/{{ ansible_local.custom.general.customer_name }}/httpdocs/spstorefront"
      register: shell_result
      when: pwadir.stdout == "true"

    - name: "Playbook - run npm build - Shell Standard Output"
      debug:
        var: shell_result.stdout_lines
      when: pwadir.stdout == "true"

    - name: "Playbook - run npm build - Shell Standard Error"
      debug:
        var: shell_result.stderr
      when: pwadir.stdout == "true"
